### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SimonLeclere** [AngeloCore/discord-buttons#1]
Hey, you should add in your documentation a section explaining how to see the buttons. For example you could explain how to enable experiments, either via a plugin for betterdiscord, or via code injection in the console.

**Comment by StoyanKolevDev** [comment]
## Is easy, just do this:

<br>

**1** - `CTRL` + `SHIFT` + `I`
**2** - Go to console
**3** - Paste this code:
```js
webpackJsonp.push([[999],{"l":(m,e,r)=>{for(k in r.c)(m=r.c[k].exports)&&m.default&&m.default.isDeveloper==0&&Object.defineProperty(m.default,"isDeveloper",{get:()=>1})}},[["l"]]])
```
**4** - Click enter
**5** - Close the Developer Tools
**6** - Go to `User Settings`
**7** - Go to `Experiments`
**8** - Go to `Desktop Bot UI Kit Buttons`
**9** - Click and select `Treatment 1`
**10** - Done

**Comment by AngeloCore** [comment]
# THIS IS AGAINST THE DISCORD TOS, DON'T DO THAT!!!

**Comment by AngeloCore** [comment]
Just apply for discord tester

**Comment by gaetan20** [comment]
> Just apply for discord tester

But how can I apply to discord tester ?

**Comment by SimonLeclere** [comment]
Hey, I know how to do it and I'm already a discord tester ^^ I was rather suggesting to add this to the documentation for those who wouldn't know how to do it.

**Comment by gaetan20** [comment]
> Hey, I know how to do it and I'm already a discord tester ^^ I was rather suggesting to add this to the documentation for those who wouldn't know how to do it.

Can you explain how to do ?

**Comment by AngeloCore** [comment]
![image](https://user-images.githubusercontent.com/62988428/116139380-a1a7a080-a6de-11eb-9147-5f53787ac365.png)

**Comment by gaetan20** [comment]
So Angelo how can you see the buttons ? You're not a staff

**Comment by AngeloCore** [comment]
> The easiest way is to become a discord tester by joining the discord testers server (type how to become a discord tester in google). You can also use [this plugin](https://github.com/Inve1951/BetterDiscordStuff/blob/master/plugins/discordexperiments.plugin.js) with betterdiscord or use a code injection as explained above.

Using **betterdiscord** or any other modified discord client is against the discord Terms of Service

**Comment by AngeloCore** [comment]
> So Angelo how can you see the buttons ? You're not a staff

My brother can see them
I see them from his computer

**Comment by AngeloCore** [comment]
I'm already confused
I really don't know

**Comment by DRehman-Bilal** [comment]
bruh
his brother is tester
@gaetan20

**Comment by DRehman-Bilal** [comment]
i think
