### ISSUE TITLE
clickButton doesn't emitted

### ISSUE THREAD

**Issue by garder500** [AngeloCore/discord-buttons#100]
Hello, I have a problem, indeed the clickButton event is not emit

I configured the module well because I can get the messagebuttoncollector and other functions on the message property, 
But impossible to use it because the clickButton event is not emit
What must I do?

**Comment by GodyFromDiscord** [comment]
emit it

**Comment by garder500** [comment]
> emit it

Okay, and how?

**Comment by GodyFromDiscord** [comment]
> > emit it
> 
> Okay, and how? 

You tell us, you've opened and issue just stating you've modified things, given no context compaining you can't emit it, that's on your end

**Comment by AngeloCore** [comment]
Hey, try to put your import on the ready event, Example:

```js
client.on('ready', () => {
  require('discord-buttons')(client);
  //or
  disbut(client);
})
```
