### ISSUE TITLE
DiscordAPIError: Cannot send an empty message

### ISSUE THREAD

**Issue by necro-wbj** [AngeloCore/discord-buttons#106]
After I use this library, I use message.edit() when there is no content but MessageEmbed and an error occurs.

**Comment by LoneWolf6969** [comment]
You have to do it as message.edit({embed : embed, components: components })

**Comment by AngeloCore** [comment]
it's fixed in the dev version

**Comment by Itz-Hyperz** [comment]
I'm having this same issue, I cannot add buttons to my embeds, according to your above comment, should I just load the dev version?
