### ISSUE TITLE
Sending message returns [object Object]

### ISSUE THREAD

**Issue by Itz-Hyperz** [AngeloCore/discord-buttons#107]
Upon running the my bot, I could send the message via command `.createpanel` which would send a message with a button attached.

just doing `message.channel.send(panelEmbed)` works fine, no errors.
Yet when doing `message.channel.send(panelEmbed, myButton)` it throws [object Object] with no console error.

Any idea(s) as to why this happens, and is their a fix for it?

![](https://cdn.hyperz.dev/tfa99m7v.png)
![](https://cdn.hyperz.dev/7w41mqdu.png)
![](https://cdn.hyperz.dev/1vdcg2sb.png)

**Comment by Itz-Hyperz** [comment]
Update: I did add a `.setID('')` line to the `myButton` constant, and it does still throw [object Object], not sure as-to why. The button should be setup properly...

**Comment by AngeloCore** [comment]
You can send buttons like this in the dev version, in stable should be `.send({ embed: myembed, button: mybutton });`

**Comment by Itz-Hyperz** [comment]
Well, now it's not throwing [object Object], but it's not putting the button on the embed either.

**Comment by Itz-Hyperz** [comment]
![](https://cdn.hyperz.dev/6hi0nt8o.png)
![](https://cdn.hyperz.dev/rk5in0js.png)

**Comment by Itz-Hyperz** [comment]
Alrighty, I got this fixed, solution was writing it as `buttons: myButton` rather than `button: myButton`

My bad, got it fixed, thanks for the support otherwise :]

Final code for others having trouble: 

![](https://cdn.hyperz.dev/8vl2sc86.png)
