### ISSUE TITLE
Requiring the Libary with different Clients 

### ISSUE THREAD

**Issue by Rakejs** [AngeloCore/discord-buttons#108]
I want to use 2 clients so I have a client=[client1,client2] in an array
Using this causes a error
```js
require('discord-buttons')(client[i]);
require('discord-buttons')(client[i]);
```
`Error: The class/prototype returned from the extender function must e`
 With a module named `import-fresh` ,which bypasses the cache ,still causes the same error
 Are there any solutions for it?

**Comment by AngeloCore** [comment]
Ok, we will make multiple method
