### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by thunder-19** [AngeloCore/discord-buttons#110]
Can't send a empty message

**Comment by Madnesssik** [comment]
Show u'r code

**Comment by Brackzz** [comment]
sillllllllllllllllly show ur code now

**Comment by EwoX07** [comment]
`DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (/root/karaoke/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (/root/karaoke/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'patch',
  path: '/channels/788819127854170112/messages/860221285434654750',
  code: 50006,
  httpStatus: 400
}`

he probably meant this error

**Comment by Brackzz** [comment]
Okk now look @Madnesssik Help him cause I am retarded :)

**Comment by Brackzz** [comment]
Wait nvn that still aint his code

**Comment by AngeloCore** [comment]
Fixed

**Comment by EwoX07** [comment]
still got the same error tho

**Comment by thunder-19** [comment]
yeah

**Comment by thunder-19** [comment]
Its messing with my client, its somehow stating it cant send a empty message.
https://i.imgur.com/kWmzh7M.png

**Comment by AngeloCore** [comment]
Its fixed in the dev version 🤔

**Comment by thunder-19** [comment]
So do i have to wait for a update?

**Comment by AngeloCore** [comment]
yes, `npm i AngeloCore/discord-buttons#dev`

**Comment by thunder-19** [comment]
I get this error when trying to install dev version
https://i.imgur.com/p6SM0T9.png

**Comment by AngeloCore** [comment]
Looks like you dont have git installed, install git or wait for the publish!

**Comment by thunder-19** [comment]
ah okay
