### ISSUE TITLE
Error on button.reply.send function

### ISSUE THREAD

**Issue by Assassin-1234** [AngeloCore/discord-buttons#14]
I'm using button.reply.send() in my code but I'm getting a 404 error (refer to image)
![image](https://user-images.githubusercontent.com/68866924/119793358-24956400-bef4-11eb-819e-e216c6f1c4ad.png)

code-
```js
return button.reply.send({ embed: embed, ephemeral: true });
```

**Comment by RamWrath** [comment]
if button.defer() in clickbutton, delete button.defer()

**Comment by RamWrath** [comment]
> if button.defer() in clickbutton, delete button.defer()

Use button.defer() only where needed to avoid errors

**Comment by AngeloCore** [comment]
Looks like you already replied...
Use `button.reply.edit` Instead

**Comment by Assassin-1234** [comment]
I fixed it but I'm facing this problem now,
```js
const cmdsEmbed = new Discord.MessageEmbed()
			.setTitle(`${category.slice(0, 1).toUpperCase()}${category.slice(1)} Commands`)
			.setDescription(cmds)
			.setColor('RANDOM')
			.setFooter('Page 1/1');
		return button.reply.send(cmdsEmbed, true);
```
^^ my code, it sends this-
![image](https://user-images.githubusercontent.com/68866924/119822328-2883af00-bf11-11eb-8c0f-c5d93b37e803.png)

**Comment by Assassin-1234** [comment]
I also tried the message options method, still getting the same thing

**Comment by RamWrath** [comment]
> I also tried the message options method, still getting the same thing

```js
return button.reply.send({embed: cmdsEmbed, ephemeral: true});
```
like this?

**Comment by Assassin-1234** [comment]
yep, the message is not ephemeral in the message options method either, 
![image](https://user-images.githubusercontent.com/68866924/119822986-e9a22900-bf11-11eb-8f3c-beea0cae8693.png)

can you please try it yourself and let me know if this is only me or something

**Comment by Assassin-1234** [comment]
![image](https://user-images.githubusercontent.com/68866924/119823104-0d656f00-bf12-11eb-95c8-268ae851de66.png)
full code

**Comment by Galaxy-Coding** [comment]
Please join the discord so I can help you real time

**Comment by Assassin-1234** [comment]
I'm already in the server, my tag is `AssassiN#0002`

**Comment by Assassin-1234** [comment]
also why not here I mean I already described everything, its also plausible that its a bug

**Comment by Assassin-1234** [comment]
alright so I have pinpointed the bug, `button.reply.send()` cannot send embeds for some reason, I also tried it with the MessageOptions method but it still gives me object object. @AngeloCore

**Comment by Galaxy-Coding** [comment]
it works for me @Assassin-1234

**Comment by AngeloCore** [comment]
If you have a bug, report to the bugs channel!

**Comment by Assassin-1234** [comment]
can you please show your code?
