### ISSUE TITLE
Discord.js-light

### ISSUE THREAD

**Issue by V1rtuaI** [AngeloCore/discord-buttons#22]
Could you add support for discord.js-light?

**Comment by Galaxy-Coding** [comment]
Sounds like a good idea, but i’m guessing there are priorities.

**Comment by a9ex** [comment]
I also use d.js-light, try [a9ex/discord-buttons-djslight](https://github.com/a9ex/discord-buttons-djslight)
works for me

**Comment by xHyroM** [comment]
It's supported. You use discord.js-light client

**Comment by a9ex** [comment]
this will not work because members and channels are not cached by default with d.js-light
channel and clicker will return null for clickButton

**Comment by AngeloCore** [comment]
And why doesn't it work with discord.js-light?

**Comment by ZeroDiscord** [comment]
> And why doesn't it work with discord.js-light?

https://github.com/AngeloCore/discord-buttons/issues/22#issuecomment-850699974_

**Comment by BliiTzZ** [comment]
This will be fixed in a future update

**Comment by colenh** [comment]
I still have this error.

**Comment by a9ex** [comment]
Issue fixed on v2.5.0 (since 14 days), with fetch()

**Comment by xMinota** [comment]
I swear this doesn't still work
