### ISSUE TITLE
maybe an inline .onClick callback?

### ISSUE THREAD

**Issue by Xapu1337** [AngeloCore/discord-buttons#24]
This might be very useful for something like message collectors to abort the collector
so my idea is a .onClick constructor option something like:
```js
 const button = new MessageButton()
          .setStyle("red")
          .setLabel('ABORT')
          .setID('tester_button')
          .onClick(async(button) => { console.log(button.id); })
```

**Comment by EhsanFox** [comment]
i really don't see it any help, we already have Collectors fine and nice working.

**Comment by Xapu1337** [comment]
> i really don't see it any help, we already have Collectors fine and nice working.

But can collectors abort a message collector for example?

**Comment by Xapu1337** [comment]
A specific MessageCollector.
A collector that is called by a function and instead to wait or write "ABORT" I want to create a button that can be clicked to stop the message collector that is inside the function
and from what I understand you can only stop one collector. Or can you add ButtonCollector onto of a message collector?

**Comment by xHyroM** [comment]
@Xapu1337 use `clickButton` event or `MessageCollector`

**Comment by xHyroM** [comment]
https://discord-buttons.js.org/button_onclick https://discord-buttons.js.org/createbuttoncollector
