### ISSUE TITLE
Cannot use split MessageOption.

### ISSUE THREAD

**Issue by Koyamie** [AngeloCore/discord-buttons#26]
When sending a message, passing a split MessageOption is generating a Discord API Error: cannot send an empty message.

**Comment by Koyamie** [comment]
> can you please send your code?

```js
message.channel.send('hi', {
  split: {
    maxLength: 1950,
  },
}).catch(console.error);```

Basically lol

**Comment by AngeloCore** [comment]
It will be fixed on the next update, today or tommorow

**Comment by AngeloCore** [comment]
Fixed, thanks for using our package
