### ISSUE TITLE
disable button after click , or delete it

### ISSUE THREAD

**Issue by Buazeez** [AngeloCore/discord-buttons#29]
hello, first is there a way to disable the button after click ( in _clickButton_ event ) like button.disable
second, I can't delete only the button like the embed by using
```javascript
button.message.edit({ button: null })
```

**Comment by xHyroM** [comment]
You can't delete buttons because discord
You only Can edit button like:
```js
var btn = new MessageButton()
btn = btn.setDisabled()
button.message.edit("message", btn)
```

**Comment by russellmwolf** [comment]
@Buazeez you can do `await button.message.edit({ component: null })` to delete the button
