### ISSUE TITLE
Including user id in the clicker object in the ButtonEvent class

### ISSUE THREAD

**Issue by BrabhamJ** [AngeloCore/discord-buttons#31]
`this.clicker = {user_id: data.member.user.id};`

For some reason `clicker.member` and `clicker.user` are `null` for me and the snowflakes aren't resolving. 

It'd be nice to have the user id to use as a fallback in the instance the snowflakes don't resolve.

**Comment by xHyroM** [comment]
Need enable discord intents `SERVER MEMBER INTENT` in discord dev panel.
`button.clicker.member`

**Comment by BrabhamJ** [comment]
> Need enable discord intents `SERVER MEMBER INTENT` in discord dev panel.
> `button.clicker.member`

It is enabled, and `button.clicker.member` is `null` sorry for not clarifying.

I think either way having the user id is handy.

**Comment by AppEternal** [comment]
#30 - It's possible you're not caching the users with discord.js or the user hasn't had a chance to get cached by the bot.
