### ISSUE TITLE
Suggestion to change button color names

### ISSUE THREAD

**Issue by vervee** [AngeloCore/discord-buttons#36]
I think it would be better to use `primary`, `secondary`, `error` (or `destructive` like on official image from Discord API docs) etc for `.setStyle()` method rather than `blurple`, `gray`, `red`

![image](https://user-images.githubusercontent.com/52330778/120079765-20b53d80-c0be-11eb-93d1-98a2cc75dae1.png)

**Comment by Galaxy-Coding** [comment]
My idea is that both is supported, since migrating can be difficult.
