### ISSUE TITLE
MessageButton.setDisabled always makes button disbled. No way to make it enabled again

### ISSUE THREAD

**Issue by TheArmagan** [AngeloCore/discord-buttons#37]
## There is a basic logic error, easly can be fixed.

> ### I am currently modifying the prototaype manually:
> ```js
> MessageButton.prototype.setDisabled = function (d) {
>   this.disabled = Boolean(d);
> }
> ```
> you can just put var into Boolean, boolean does everthing for you.

> ## Original code:
> 
> ```js
> MessageButton.prototype.setDisabled = function (d) {
>   this.disabled = Boolean(d || true);
> }
> ```
> there is no way to make it false.

**Comment by xHyroM** [comment]
Fixed in new update

**Comment by xHyroM** [comment]
https://github.com/AngeloCore/discord-buttons/pull/34

**Comment by TheArmagan** [comment]
> #34

yep, cool!
