### ISSUE TITLE
No need for the ['click_to_function'] in URL.

### ISSUE THREAD

**Issue by gatelogic** [AngeloCore/discord-buttons#42]
When using a URL button if you use the README/Original code, it will error saying that `DiscordAPIError: Invalid Form Body
components[0].components[0].url: Scheme "[click_to_function](https" is not supported. Scheme must be one of ('http', 'https').`.

Instead it should look like this.
```
let btn = new disbut.MessageButton()
      .setStyle('url') //default: blurple
      .setLabel('My Second Button!') //default: NO_LABEL_PROVIDED
      .setURL('https://npmjs.com/discord-buttons') //note: if you use other style you must provide id using .setID('myid')
```

**Comment by BliiTzZ** [comment]
Documentation has not been updated. We are conscientious of this and the documentation will be updated to the next version
