### ISSUE TITLE
Multiple Button Collectors running at one time

### ISSUE THREAD

**Issue by nab138** [AngeloCore/discord-buttons#50]
Im using discord-buttons for my bot and it works great, until more then one user tries to use the commands with button collectors at the same time. When two button collectors are active, the following happens: When any button is clicked it works fine. But If you try to click a different button, it ends the collector properly but doesn't return the info. I'm using a command handler and doing y/n prompt so I can't really do client.on listeners for buttons and don't want to as it makes my code look kinda messy. Im not really sure what to do about that.

**Comment by nab138** [comment]
I even tried adding the user id to the ID of the button so the buttons dont have the same id, and the same problem persists

**Comment by nab138** [comment]
Dug into your code and found that the collector.end event was emitted to all collectors. Solved by using a recursive function to restart the listener if it ends with no buttons returned.

**Comment by Tixyel** [comment]
Did you manage to solve this problem?

**Comment by rayzdev** [comment]
> Did you manage to solve this problem?

Yes, he did manage to resolve his issue. Check the message above.
