### ISSUE TITLE
Disable a button when it has been selected.

### ISSUE THREAD

**Issue by flyflow84** [AngeloCore/discord-buttons#51]
Hi friend,
Already, I wanted to thank you for the buttons, it is very practical.
I would like to know if it is possible to disable the "Yes" button when someone selects it so that they can only select "No" if they change their mind or vice versa.
So when he selects the "No" button it will be disabled, the "Yes" button will be enabled.
Obviously, it is an individual choice of the blow each member has the choice to independently choose "Yes" or "No.

Thanks you in advance :)

**Comment by EhsanFox** [comment]
Hey, You can edit your old message with new buttons at the moment, and in your new message u can have whatever buttons you want(1 disabled and 1 not)

Also we would be more thankfull if you ask your questions in support server(at the end of the Readme)
And close your issue in here!
