### ISSUE TITLE
Error: "animated is not defined"

### ISSUE THREAD

**Issue by Cannicide** [AngeloCore/discord-buttons#65]
Whenever I attempt to add an emote to my buttons, I get this error:

`ReferenceError: animated is not defined
    at MessageButton.setEmoji (/node_modules/discord-buttons/src/v12/Classes/MessageButton.js:67:9)`

Looking at the code, it does seem to be the case that an `animated` variable is used [here](https://github.com/AngeloCore/discord-buttons/blob/main/src/v12/Classes/MessageButton.js#L67) but is never defined. I assume this was intended to be the second parameter of the `setEmoji` method, but has not yet been added.

----

Discord.js version: 12.5.3
discord-buttons version: 3.1.0

**Comment by keronmaharaj** [comment]
Fixed!

**Comment by AngeloCore** [comment]
`npm i discord-buttons@latest`
