### ISSUE TITLE
the clickButton event is not triggered after bot restarted

### ISSUE THREAD

**Issue by eslym** [AngeloCore/discord-buttons#71]
Steps to reproduce:
1. Send a message with button
2. Click the button and the event listener is working
3. Restart the bot
4. Click the button but the event listener is not working
5. Send a new message with button
6. Click the button and the event listener is working
7. Click the button at previous message and the event listener is working again

**Comment by Blade67** [comment]
This is expected behavior. After restart, your bot looses context of its past messages. If you want them to keep working after restart, cache the relevant message IDs.

**Comment by Larkify** [comment]
This isn't an issue, it's expected as the messages aren't partial. This happens in regular Djs for reaction add events and message delete etc. Just do what @Blade67 said and cache the relevant message IDs so that you can respond to them after a restart.

**Comment by Tixyel** [comment]
How i solve this?

**Comment by russellmwolf** [comment]
For anyone running into this, I spent a while digging and found a a solution but I wouldn't say it's perfect. 

If you send a message with a button via a discord.js bot and restart the server/app running discord.js, discord.js will not pick up subsequent button clicks if the message was sent via DM; it will pick up subsequent button clicks if the message was sent to a public server/guild channel the bot is in.

To solve this, it's not *ideal*, but if you have a list of users who you've had a DM with (i.e. you're saving the user IDs of who you send messages to), you can iterate over your stored Discord user IDs, fetch the user via discord.js, then call `user.createDM()`

something like
```
client.once('ready', async () => {
  const discordUserIds = ['123', '456', '789'] // You'd be fetching these from your database or another data source

  await Promise.all(discordUserIds
    .map(async dicsordUserId => {
      const user = await discord.users.fetch(id, { force: true })
      await user.createDM()
    }))
})

```
