### ISSUE TITLE
Question about reply

### ISSUE THREAD

**Issue by DiaxManPl** [AngeloCore/discord-buttons#73]
Is there any way to make inline reply with buttons?

**Comment by xHyroM** [comment]
inline reply supported only in djs v13

**Comment by DiaxManPl** [comment]
Ok

**Comment by AngeloCore** [comment]
Soon `discord-reply` will support  buttons!

**Comment by DiaxManPl** [comment]
Soon, which is when?

**Comment by Assassin-1234** [comment]
You can extend your own message to get inline replies if you want, other than that I dont think there is an option
