### ISSUE TITLE
Error when calling createButtonCollector

### ISSUE THREAD

**Issue by SCDerox** [AngeloCore/discord-buttons#8]
Hello,

If I call the `createButtonCollector()` function on an message object I get the following error: `TypeError: this.client.incrementMaxListeners is not a function`. After I removed the line in `ButtonCollector.js` the following error occurred: `TypeError: this.client.decrementMaxListeners is not a function` when someone reacted to the buttons. 
After also removing that line everything worked fine.

Thank you very much ^^

**Comment by AngeloCore** [comment]
If you have a bug, report to the bugs channel!
