### ISSUE TITLE
discord-buttons not compatible with discord.js typings

### ISSUE THREAD

**Issue by GalaxySH** [AngeloCore/discord-buttons#80]
Simply put, either the discord.js types are not properly extended to include components, or they are not at all.

Looking at the actual typings for discord-buttons shows that there are extended message options interfaces, but it doesn't change the inherited types of the discord.js client.

**Comment by AngeloCore** [comment]
We are not good with typescript, feel free to make pr...

**Comment by AngeloCore** [comment]
We will fix this on the next majority version
