### ISSUE TITLE
discord.js message editing

### ISSUE THREAD

**Issue by PrimeX09** [AngeloCore/discord-buttons#81]
Message Editing isn't working on the latest version of this repository.
My Setup: DiscordJS: 12.2.0 | Discord-Buttons: 3.2.1

After calling the message edit, discord will mark the message as read, but nothing will change. Also no error apper.
On my 2nd Test Bot, with same Discord JS Version an Version 2.4.1 of this repository everything works fine.
.

**Comment by zLevii** [comment]
You should try and catch your error, also if it works fine on your 2nd bot then it's nothing to do with the npm and its something with your code, join the discord for more assistance at **https://discord.gg/AWq2uPbsdc**
