### ISSUE TITLE
TypeError: (intermediate value).setStyle(...).setLabel(...).setID(...).setUrl is not a function

### ISSUE THREAD

**Issue by KodeNoleg** [AngeloCore/discord-buttons#82]
I keep getting this error, please help.

**Comment by Madnesssik** [comment]
Hey, can you show me u'r code?

**Comment by tayron1** [comment]
Isn't it `.setURL("URLGOESHERE")`?

**Comment by zLevii** [comment]
If you're trying to use `.setURL()` along with `.setID()` then it's not gonna work . If it's not that then please paste your code here or in a bin.
