### ISSUE TITLE
Library appears to mess with message edit or send requests even when a button isn't being added.

### ISSUE THREAD

**Issue by NeonCoding** [AngeloCore/discord-buttons#85]
I'm using the library in a bot, and it is causing issues to occur in unrelated sections of code - whenever I am editing a message or sending one with an embed, I can no longer send it with the form of `message.edit(embedVariable)` - This causes a DiscordAPIError stating I can't send an empty message - I have to change the format to `message.edit({embed: embedVariable})` to get it to work properly - I have tested with the library not required in a file, and it resolves the issue.

**Comment by AngeloCore** [comment]
Check issue #92
