### ISSUE TITLE
Clicker user get null value

### ISSUE THREAD

**Issue by DECO190** [AngeloCore/discord-buttons#86]
When the second person clicks on the button, the callback object clicker user get null value 

![image](https://user-images.githubusercontent.com/64938482/121748552-93231600-cadf-11eb-9318-8ffee03de726.png)
![image](https://user-images.githubusercontent.com/64938482/121748643-b221a800-cadf-11eb-8a22-b2733c2db112.png)

**Comment by es183923** [comment]
you're supposed to do `button.clicker.fetch()` first.

**Comment by zLevii** [comment]
You need to use `await button.clicker.fetch()` first in order to get the clicker

**Comment by MrEnxo** [comment]
await button.clicker.fetch() does not exist

**Comment by MrEnxo** [comment]
it does not exist if you install with npm.

**Comment by zLevii** [comment]
It does exist. What's your code?

**Comment by MrEnxo** [comment]
my code is legit await button.clicker.fetch() it does not exist

**Comment by MrEnxo** [comment]
so apparently `npm i discord-buttons` installs a outdated version

**Comment by zLevii** [comment]
> my code is legit await button.clicker.fetch() it does not exist

You need to use it in the `clickButton` event.

**Comment by zLevii** [comment]
> so apparently `npm i discord-buttons` installs a outdated version

Try `npm i discord-buttons@latest`
