### ISSUE TITLE
I'm having button is not defined when the clickButton event is executed

### ISSUE THREAD

**Issue by Tixyel** [AngeloCore/discord-buttons#91]
(node:11928) UnhandledPromiseRejectionWarning: ReferenceError: button is not defined

**Comment by Crni39** [comment]
Error @Tixyel ?

**Comment by Tixyel** [comment]
Here https://sourceb.in/8PffTPzt0M

**Comment by Crni39** [comment]
> Here https://sourceb.in/8PffTPzt0M

Here fixed: https://sourceb.in/BcIlgIfrqb
Don't use bots, disbut and MessageButton..
