### ISSUE TITLE
channel.send parameters are being misinterpreted

### ISSUE THREAD

**Issue by MoonlightCapital** [AngeloCore/discord-buttons#95]
I had some code that looked like this:

```js
const channel = client.channels.cache.get((client.settings.globalLogChannels.find(c=>c.name === channeltype) || {}).channel)

	if(!channel) return

	const response = await resolveString(type, client, data)

	const {str, embed} = await parseResponse(client, response)

	await channel.send(str, embed)
```

On the last line, you see I'm trying to send a message in the channel, however, after implementing the discord-buttons package, something got messed up, and my bot started spamming its error logs with the following:

```
TypeError: Cannot set property 'content' of null
    at APIMessage.resolveData (/usr/src/moonlightbot/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:122:34)
    at ExtendedTextChannel.send (/usr/src/moonlightbot/node_modules/discord-buttons/src/v12/Classes/TextChannel.js:19:68)
    at MoonlightClient.module.exports [as glog] (/usr/src/moonlightbot/src/includes/glog.js:152:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

In that send, either `str` or `embed` can be null, depending on what I want to send (it's a dynamic log feature that may use embeds or simple text). Both variables cannot be null at the same time. This error seems to pop up only when the first argument is null. I fixed it the following way:

```js
await channel.send({content: str ?? '', embed: embed})
```

It works, but it's very ugly, and makes me suspect I have to make other changes to my code in order to integrate with the buttons library perfectly. Please make parameters work like they would without the library changes.

**Comment by BliiTzZ** [comment]
Thank you for your attention to the module and for this bug feedback. We take your request into account and will look for a solution.

**Comment by AngeloCore** [comment]
We will fix this on the next majority version
