### ISSUE TITLE
Bug whit discord.js light

### ISSUE THREAD

**Issue by TheDiego845** [AngeloCore/discord-buttons#99]
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './v3/Classes/MessageButton'
Require stack:
- C:\Users\DMART\Desktop\Bot\node_modules\discord-buttons\src\index.js
- C:\Users\DMART\Desktop\Bot\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\DMART\Desktop\Bot\node_modules\discord-buttons\src\index.js:51:32)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\DMART\\Desktop\\Bot\\node_modules\\discord-buttons\\src\\index.js',
    'C:\\Users\\DMART\\Desktop\\Bot\\index.js'
  ]
}

**Comment by Vexcited** [comment]
Hello ! 
I fixed this bug with this:
```js
// We take the real version of discord.js
const { version } = require("discord.js");
// We require discord.js-light who will overwrite the discord.js version.
const Discord = require("discord.js-light");
// We backup the real version of discord.js that was modified by discord.js-light.
Discord.version = version;

/* And now you're good to go ! */

const client = new Discord.Client({
	cacheGuilds: true,
	cacheChannels: true,
	cacheOverwrites: true,
	cacheRoles: true,
	cacheEmojis: false,
	cachePresences: false
});
// Don't forget to require (initialize) it after initializing the client.
require("discord-buttons")(client);
```

Then in your command
```js
const buttons = require("discord-buttons");
const button = new buttons.MessageButton() // etc... just like in the documentation !
```

Hope it will help !
I will write a fork package of this package. The package I'll write will replace every `discord.js` requires by `discord.js-light` requires.

**Comment by TheDiego845** [comment]
Thanks a lot many days waiting thank you

**Comment by Vexcited** [comment]
No problem but now me too a have a problem.

When I try to use the event clickButton, I don't have any data (except client).
The id, clicker, message, etc... are undefined.

My code (it's just from the documentation so i don't know)
```js
client.on("clickButton", async (button) => {
    console.log("Clicked " + button.id);
});
```
Only the button.client is not defined.
So, yes me too I need help now.

**Comment by AngeloCore** [comment]
Fixed
